### ISSUE TITLE
workflow_name get lost by orphan processes

### ISSUE THREAD

**Issue by gustavo-fdte** [flow-build/engine#67]
**What happened**: When an engine picks an orphan process, the workflow_name get lost. This makes the activity manager event for this process not to have this information.

**What you expected to happen**: Preserve the workflow_name even during orphan processes.

**How to reproduce it (as minimally and precisely as possible)**: Create a process, stop the engine while the process is still running (it cannot be waiting), restart the engine.

**Environment**:
- version: 2.5.0

**Comment by brunolnetto** [comment]
**Solution:** 
1) Validate blueprint before starting;
2) If force create, validade before starting;

**Comment by gustavo-fdte** [comment]
> **Solution:**
> 
> 1. Validate blueprint before create;
> 2. If force create, validade before starting;

Not a solution, o bug origin is not related to blueprint structure (therefore, blueprint validation won't solve, because there is nothing wrong there) nor the process itself (so there is nothing to do during process creation). 
The problem is caused during the execution loop and the data flow between the process and the activity_manager.

**Comment by brunolnetto** [comment]
What is an orphan process?

**Comment by gustavo-fdte** [comment]
> What is an orphan process?

Orphan process is a process without an engine executing it. There are some reasons that causes a process to become orphan, usually related to engine execution or persistence.
