### ISSUE TITLE
Abort does not block the process for update

### ISSUE THREAD

**Issue by gustavo-fdte** [flow-build/engine#68]
**What happened**:  A process continues to run even after being aborted.
This happens when the process loop is faster than the update table.

**What you expected to happen**: A process should always stop when aborted.

**How to reproduce it (as minimally and precisely as possible)**: Create a blueprint with circular reference on a setToBag node. Call the abort method and check the process status.

**Anything else we need to know?**: The issue abort method does not block the process for update while transacting. 

**Environment**:
- version: 2.5.0

**Comment by lucasfernandeso** [comment]
## Problema
A tentativa de abortar o processo falha se o processo estiver em execução. Nesse caso, a engine que está executando o processo o bloqueiou no \_\_inner_loop (process.js, linha 377), impedindo que qualquer alteração seja feita neste processo e em seu processState.
#### Atual
Sequencia de um pedido de abortar processo feito para a engine.
```mermaid
sequenceDiagram
    participant Client
    participant Engine
    participant ProcessManager
    participant Process
    participant ProcessState
    participant ActivityManager
    Client ->> Engine: abortProcess
    Engine ->> ProcessManager: abortProcess
    loop Each Process
        ProcessManager ->> Process: fetch
        Process -->> ProcessManager: return
        ProcessManager ->> Process: abort
        Process ->> Process: getNextStepnumber
        Process ->> ProcessState: contructor
        Process ->> ActivityManager: interruptActivityManagerForProcess
        ActivityManager -->> Process: return
        Process ->> ProcessState: save
        Note right of ProcessState: here where it fails, db is locked
        ProcessState -->> Process: return
        Process ->> Process: notifyProcessState
        Process -->> ProcessManager: return
    end
    ProcessManager -->> Engine: return
    Engine -->> Client: return
```
Nota: A engine expõe uma função de abort que aceita um único processo, todavia, o processManager está pronto para aceitar uma lista de processos como input.
## Proposta de Solução
O que precisamos é parar o loop de execução antes de parar o processo, ou sinalizar o loop de execução do desejo de parar o processo.
Para isso, utilizaremos a tabela de timers.
1. O método de abortProcess cria um timer ativo, porém vencido, vinculado ao processo.
2. Caso o processo esteja em execução, o execution_loop, antes de abrir uma transação para a execução do próximo nó, verificará a existência de algum timer vencido para o processo em questão.
   a. caso exista, a engine executará o timer, que irá abortar (ou expirar) o processo e então sair do loop de execução.
3. Caso o processo não esteja em execução o heartbeat da engine se encarregará de executar o timer.
A solução proposta resolve um débito técnico da engine que é o de não expirar processos em execução.
#### Abort Process
```mermaid
sequenceDiagram
    participant Client
    participant Engine
    participant ProcessManager
    participant Timer
    Client ->> Engine: abortProcess
    Engine ->> ProcessManager: abortProcess
    loop Each Process
        ProcessManager ->> Timer: create timer
        Timer -->> ProcessManager: return
    end
    ProcessManager -->> Engine: return
    Engine -->> Client: return
```
#### Execution Loop
```mermaid
stateDiagram-v2
   state timerState <<choice>>
   state timerReason <<choice>>
   [*] --> timer.getTimersByResource('Process',pid)
   timer.getTimersByResource('Process',pid) --> timerState
   timerState --> Process.inner_loop(): no timers
   timerState --> Process.timeout(): has timer
   Process.timeout() --> timerReason
   timerReason --> Process.expireProcess(): undefined
   timerReason --> Process.abort(): abort
```
### Implementação
1. Criar um método na classe Timer para retornar timers ativos por resourceId
2. Alterar o método abortProcess do process_manager para criar um timer para o process_id passado, passando para o campo params o actor_data e também um campo reason=abort e 0s para vencer
3. No process.execution_loop, logo depois de entrar no while, incluir uma chamada que consulta timers vencidos e ativos para o processo e chama o método timeout().
   a. Garantir que o execution_loop sai do while depois disso.
4. Alterar o método timeout() para avaliar a reason. Se for abort, chama o método abort(), caso contrário segue normalmente.
   a. No método timeout() remover a condição de que processos RUNNING não podem ser expirados
5. Ajustar os testes de abort, os processos não são mais abortados na mesma transação, a chamada de abort passa a retornar somente um ACK do pedido. A confirmação do abort vem do notifyProcessState com state INTERRUPTED. Esse intervalo não deveria se superior a um heartbeat.

Autor: @gustavo-fdte
