### ISSUE TITLE
Add indices to big tables

### ISSUE THREAD

**Issue by brunolnetto** [flow-build/engine#72]
I know, indices are for read-only, not read-write tables. But they are so so helpful for analytics that maybe it should be on the original engine table already before the DBA makes a replica.

Big tables are: `process_state`, `activity_manager`, `activity`

The engine migrations folder is here: 
https://github.com/flow-build/engine/tree/master/db/migrations

This issue might help.
https://github.com/knex/knex/issues/322

**Comment by gustavo-fdte** [comment]
On 3 sep 2021 several indexes were added to the default engine migrations.
If there are generic indexes that should improve any query related to process execution, please specify.

**Comment by brunolnetto** [comment]
I ask you to post the aforementioned commits with claimed added indexes.  As I mention in my main post, the required necessary columns to have indexes is research task defined by the tables below.

Big tables are: process_state, activity_manager, activity
